import render from "../../src/renderers/render"
import { ContentType, Locale } from "contentful-management"

describe("render()", () => {
  const contentTypes: ContentType[] = [
    {
      sys: {
        id: "myContentType",
      },
      fields: [
        {
          id: "arrayField",
          name: "Array field",
          required: true,
          validations: [{}],
          items: {
            type: "Symbol",
            validations: [
              {
                in: ["one's", "of", "the", "above"],
              },
            ],
          },
          disabled: false,
          omitted: false,
          localized: false,
          type: "Array",
        },
      ],
      description: "",
      displayField: "",
      name: "",
    } as ContentType,
  ]

  const locales: Locale[] = [
    {
      name: "English (US)",
      fallbackCode: null,
      code: "en-US",
      default: true,
      sys: {} as Locale["sys"],
    } as Locale,
    {
      name: "Brazilian Portuguese",
      fallbackCode: "en-US",
      code: "pt-BR",
      default: false,
      sys: {} as Locale["sys"],
    } as Locale,
  ]

  it("renders a given content type", async () => {
    expect(await render(contentTypes, locales)).toMatchInlineSnapshot(`
      "// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

      import { Asset, Entry } from \\"contentful\\"
      import { Document } from \\"@contentful/rich-text-types\\"

      export interface IMyContentTypeFields {
        /** Array field */
        arrayField: (\\"one's\\" | \\"of\\" | \\"the\\" | \\"above\\")[]
      }

      export interface IMyContentType extends Entry<IMyContentTypeFields> {
        sys: {
          id: string
          type: string
          createdAt: string
          updatedAt: string
          locale: string
          contentType: {
            sys: {
              id: \\"myContentType\\"
              linkType: \\"ContentType\\"
              type: \\"Link\\"
            }
          }
        }
      }

      export type CONTENT_TYPE = \\"myContentType\\"

      export type LOCALE_CODE = \\"en-US\\" | \\"pt-BR\\"

      export type CONTENTFUL_DEFAULT_LOCALE_CODE = \\"en-US\\"
      "
    `)
  })

  it("renders a given localized content type", async () => {
    const contentTypes: ContentType[] = [
      {
        sys: {
          id: "myContentType",
        },
        fields: [
          {
            id: "arrayField",
            name: "Array field",
            required: true,
            validations: [{}],
            items: {
              type: "Symbol",
              validations: [
                {
                  in: ["one's", "of", "the", "above"],
                },
              ],
            },
            disabled: false,
            omitted: false,
            localized: false,
            type: "Array",
          },
        ],
        description: "",
        displayField: "",
        name: "",
      } as ContentType,
    ]

    expect(await render(contentTypes, locales, { localization: true })).toMatchInlineSnapshot(`
      "// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

      import type { Entry } from \\"contentful\\"
      import type { Document } from \\"@contentful/rich-text-types\\"

      export interface IMyContentTypeFields {
        /** Array field */
        arrayField: DefaultLocalizedField<(\\"one's\\" | \\"of\\" | \\"the\\" | \\"above\\")[]>
      }

      export interface IMyContentType extends Entry<IMyContentTypeFields> {
        sys: {
          id: string
          type: string
          createdAt: string
          updatedAt: string
          locale: string
          contentType: {
            sys: {
              id: \\"myContentType\\"
              linkType: \\"ContentType\\"
              type: \\"Link\\"
            }
          }
        }
      }

      export type CONTENT_TYPE = \\"myContentType\\"

      export type LOCALE_CODE = \\"en-US\\" | \\"pt-BR\\"

      export type CONTENTFUL_DEFAULT_LOCALE_CODE = \\"en-US\\"

      export type DefaultLocalizedField<T> = Record<CONTENTFUL_DEFAULT_LOCALE_CODE, T>
      export type LocalizedField<T> = DefaultLocalizedField<T> & Partial<Record<LOCALE_CODE, T>>

      // We have to use our own localized version of Asset because of a bug in contentful https://github.com/contentful/contentful.js/issues/208
      export interface Asset {
        sys: Sys
        fields: {
          title: LocalizedField<string>
          description: LocalizedField<string>
          file: LocalizedField<{
            url: string
            details: {
              size: number
              image?: {
                width: number
                height: number
              }
            }
            fileName: string
            contentType: string
          }>
        }
        toPlainObject(): object
      }

      // When you specify a locale in contentful \`client.getEntries\`, the shape of the
      // return value is different. This adapter class unwraps LocalizedField<T> and
      // DefaultLocalizedField<T> to just T. There are also versions for ISomethingFields
      // and Entry<ISomethingFields>
      export type SpecificLocaleField<T> = T extends LocalizedField<infer F>
        ? SpecificLocaleMaybeEntry<F>
        : T extends DefaultLocalizedField<infer F>
        ? SpecificLocaleMaybeEntry<F>
        : T

      export type SpecificLocaleFields<T> = {
        [k in keyof T]: SpecificLocaleField<T[k]>
      }

      // when a content type refers to another content type with nested
      // entries or a reference field, we need to unwrap the nested
      // locales too.
      type SpecificLocaleMaybeEntry<T> = T extends Entry<infer E>
        ? SpecificLocale<Entry<E>>
        : T extends Entry<infer E>
        ? SpecificLocale<Entry<E>>
        : T extends Array<Entry<infer E>>
        ? Array<SpecificLocale<Entry<E>>>
        : T extends Asset
        ? SpecificLocale<Asset>
        : T extends Array<Asset>
        ? Array<SpecificLocale<Asset>>
        : T

      export type SpecificLocale<T extends { fields: any }> = Omit<T, \\"fields\\"> & {
        fields: SpecificLocaleFields<T[\\"fields\\"]>
      }
      "
    `)
  })

  it("renders given a content type inside a namespace", async () => {
    expect(await render(contentTypes, locales, { namespace: "Codegen" })).toMatchInlineSnapshot(`
      "// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

      import { Asset, Entry } from \\"contentful\\"
      import { Document } from \\"@contentful/rich-text-types\\"

      declare namespace Codegen {
        export interface IMyContentTypeFields {
          /** Array field */
          arrayField: (\\"one's\\" | \\"of\\" | \\"the\\" | \\"above\\")[]
        }

        export interface IMyContentType extends Entry<IMyContentTypeFields> {
          sys: {
            id: string
            type: string
            createdAt: string
            updatedAt: string
            locale: string
            contentType: {
              sys: {
                id: \\"myContentType\\"
                linkType: \\"ContentType\\"
                type: \\"Link\\"
              }
            }
          }
        }

        export type CONTENT_TYPE = \\"myContentType\\"

        export type LOCALE_CODE = \\"en-US\\" | \\"pt-BR\\"

        export type CONTENTFUL_DEFAULT_LOCALE_CODE = \\"en-US\\"
      }

      export as namespace Codegen
      export = Codegen
      "
    `)
  })
})
